### ISSUE TITLE
Dataset harmonisation error

### ISSUE THREAD

**Issue by explodecomputer** [MRCIEU/gwasglue2#40]
```
chd_id <- c( "ukb-d-I9_IHD", "finn-b-I9_CHD")
hmgcr_chd <- lapply(seq_along(chd_id), function(i){
  # create summarysets
  s <- create_summaryset(data = ieugwasr::associations(variants = hmgcr_chrpos, id = chd_id[i]), metadata = chd_metadata[[i]])
})

sapply(hmgcr_chd, \(x) min(x@ss$p))

hmgcr_chd_meta <- hmgcr_chd[2:3] %>%
  # create dataset and harmonise
  create_dataset(., harmonise = TRUE, tolerance = 0.08, action = 1) %>%
  # meta-analysis to create a new summary set
  meta_analysis(.)   
```

**Comment by ritarasteiro** [comment]
The error in the meta-analysis happens because the summary_sets don't have the same dimensions. 
The `finn-b-I9_CHD` study has two rows with exactly the same variantid, thus when harmonising using the variantid result in the summary_sets with different dims.  

``     beta      chr p        position   n  se       id              rsid   ``     
``[1,] " 0.0407" "5" "0.5465" "75103491" NA "0.0674" "finn-b-I9_CHD" ""    ``      
``[2,] "-0.0041" "5" "0.7689" "75103491" NA "0.0139" "finn-b-I9_CHD" "rs11296602"``
  ``   ea  nea  eaf       trait                                variantid    ``    
``[1,] "A" "AT" "0.98779" "Major coronary heart disease event" "5:75103491_A_AT"``
``[2,] "A" "AT" "0.32420" "Major coronary heart disease event" "5:75103491_A_AT" ``

  To @explodecomputer 
- Need to add checks to make sure that if this happen we remove one row, but  how to choose the one to remove? They have opposite effects.
- Or should we be more stringent and remove that variantid from all summarysets?

**Comment by ritarasteiro** [comment]
- sanity check when creating summaryset
- warning if there are problems with summaryset (e.g. repeated `variantids`) and suggest to run `create_summaryset` with new quality control option `qc = TRUE`.  
- if `qc = TRUE` we will deal with the problems
